#!/bin/sh
# GENERATED by bin/generate-viewer from apps/1password.conf + templates/ -- DO NOT EDIT.
# xpra --start-child: set up a passwordless gnome-keyring (Signal stores its DB
# encryption key via libsecret/safeStorage, same pattern as 1Password's 2FA token)
# BEFORE launching Signal. Must run inside dbus-run-session (the entrypoint does that).
set -u
: "${HOME:=/home/onepassword}"
export HOME

KR="$HOME/.config/1Password/.keyrings"
mkdir -p "$KR" "$HOME/.local/share"
ln -sfn "$KR" "$HOME/.local/share/keyrings" 2>/dev/null || {
  rm -rf "$HOME/.local/share/keyrings"
  ln -sfn "$KR" "$HOME/.local/share/keyrings"
}
if [ ! -e "$KR/default" ]; then
  printf '[keyring]\ndisplay-name=login\nctime=0\nmtime=0\nlock-on-idle=false\nlock-after=false\n' > "$KR/login.keyring"
  chmod 600 "$KR/login.keyring"
  printf login > "$KR/default"
fi
eval "$(printf '' | gnome-keyring-daemon --unlock --components=secrets 2>/dev/null)"

# Dark UI. App popups -- native GTK context menus AND Chromium dropdowns (via
# Electron's nativeTheme, which on Linux follows the GTK dark preference) -- do NOT
# follow the app's in-app appearance setting; they follow the GTK theme, which
# defaults light. Prefer a dark GTK theme so the popups match dark mode.
# INTERIM: forced dark. TODO: drive from the OS X appearance the Porthole client reports.
export GTK_THEME="${OP_GTK_THEME:-Adwaita:dark}"
mkdir -p "$HOME/.config/gtk-3.0"
printf '[Settings]\ngtk-application-prefer-dark-theme=1\n' > "$HOME/.config/gtk-3.0/settings.ini"
# Launch the app with its manifest-configured flags. (Electron apps typically need
# --no-sandbox here -- their setuid sandbox doesn't work in this container; GTK apps
# usually need none. Set them per-app via APP_FLAGS.)
exec 1password --disable-gpu --user-data-dir=/home/onepassword/.config/1Password
